// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restaurantBudweis.Data;

#nullable disable

namespace restaurantBudweis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219061538_DishGroupDish2")]
    partial class DishGroupDish2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("restaurantBudweis.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("restaurantBudweis.Model.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CookingTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("DishID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupDishId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GroupDishId");

                    b.ToTable("Dishs");
                });

            modelBuilder.Entity("restaurantBudweis.Model.GroupDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DishsGroupDishs");
                });

            modelBuilder.Entity("restaurantBudweis.Model.Dish", b =>
                {
                    b.HasOne("restaurantBudweis.Model.Client", null)
                        .WithMany("Dishs")
                        .HasForeignKey("ClientId");

                    b.HasOne("restaurantBudweis.Model.GroupDish", "GroupDish")
                        .WithMany("Dishs")
                        .HasForeignKey("GroupDishId");

                    b.Navigation("GroupDish");
                });

            modelBuilder.Entity("restaurantBudweis.Model.Client", b =>
                {
                    b.Navigation("Dishs");
                });

            modelBuilder.Entity("restaurantBudweis.Model.GroupDish", b =>
                {
                    b.Navigation("Dishs");
                });
#pragma warning restore 612, 618
        }
    }
}
